#ifndef DEBUG_TOGGLES_H
#define DEBUG_TOGGLES_H
#define PRINT_CURRENT_CONMAND_STATE_DEBUG

#define TARGET_MICROPHONE_DEBUG
//#define FREQUENCY_DETECTOR_RESULT_DEBUG

#define SEARCH_STATE_SONAR_CHECK_DEBUG
#define SEARCH_STATE_BUMP_CHECKING_DEBUG
#define SEARCH_STATE_BUMP_REACTION_DEBUG
#define SEARCH_STATE_SONAR_ENCROACHMENT_CHECKING_DEBUG
#define SEARCH_STATE_SONAR_ENCROACHMENT_REACTION_DEBUG
#define SEARCH_STATE_FLAME_DETECTION_DEBUG
#define SEARCH_STATE_FLAME_REACTION_DEBUG
#define SEARCH_STATE_SONAR_READING_DEBUG

#ifdef TARGET_MICROPHONE_DEBUG || #ifdef FREQUENCY_DETECTOR_RESULT_DEBUG || \ 
		#ifdef SEARCH_STATE_SONAR_CHECK_DEBUG || #ifdef SEARCH_STATE_BUMP_CHECKING_DEBUG \
		#ifdef SEARCH_STATE_BUMP_REACTION_DEBUG || #ifdef SEARCH_STATE_SONAR_ENCROACHMENT_CHECKING_DEBUG \
		#ifdef SEARCH_STATE_SONAR_ENCROACHMENT_REACTION_DEBUG || \
		#ifdef SEARCH_STATE_FLAME_DETECTION_DEBUG || #ifdef SEARCH_STATE_FLAME_REACTION_DEBUG || \
		#ifdef SEARCH_STATE_SONAR_READING_DEBUG
	#define DEBUG_PRINTING
#endif

#endif
